module.exports = {
	ActionTypes: {
		JUGAR_POSICION: "JUGAR_POSICION",
		COMPROBAR_GANADOR: "COMPROBAR_GANADOR",
		RESETEAR: "RESETEAR",
		GUARDAR_HISTORIA: "GUARDAR_HISTORIA",
		MOSTRAR_HISTORIA: "MOSTRAR_HISTORIA"

	},
	CHANGE_EVENT: 'change',
	JUGADORX : "jugador 1 - las X",
	JUGADOR0 : "jugador O - las O"
}